# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: tobiastac
# "service" is the name of this project. This will also be added to your AWS resource names.
service: mailer

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: sa-east-1

build:
  esbuild:
    minify: true
    bundle: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'

functions:
  sendMail:
    handler: src/functions/sendMail.handler
    events:
      - httpApi:
          path: /send
          method: POST
